### PR TITLE
Update export and import to fix bugs

### LINKED ISSUE #147: Export command to .csv file creates a corrupted file
image

Currently, the export command allows an input with no filename. This creates a filename called image.

This causes the following error.
image

I think we can make it such that we do not specify the .csv format for `export` command and make it export to a csv file.

### LINKED ISSUE #148: Export command does not produce a file with csv extension when not specified in command
image

produces a file with no csv extension.

image

This issue should be related to #147 .

### LINKED ISSUE #151: Import requires no blank line in the csv file
image

When my csv file is as such, it returns me this error. 

image

Since the error message mentions `names `but there is no `name` field in the parameter, users might get confused. 

A simple fix could be to include the constraint in the user guide and could also change the error message to `There should be no preceding blank lines in the .csv file.` (along those lines)

### LINKED ISSUE #153: Import command rewrites all the contacts with the import data
The current behavior of the `import` command rewrites existing data in the address book. 

I believe that would be appropriate but perhaps can update the user guide to reflect that.

### LINKED ISSUE #157: Import uncaught exception when missing WeeksPresent column
This is my csv file:
image

 Trying to import this file will cause an array out of bound exception which is not caught.

```
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 7 out of bounds for length 7
        at seedu.address.logic.commands.ImportCommand.parsePerson(ImportCommand.java:90)
        at seedu.address.logic.commands.ImportCommand.execute(ImportCommand.java:61)
        at seedu.address.logic.LogicManager.execute(LogicManager.java:51)
        at seedu.address.ui.MainWindow.executeCommand(MainWindow.java:199)
        at seedu.address.ui.CommandBox.handleCommandEntered(CommandBox.java:51)
        ... 56 more
```

### LINKED ISSUE #184: Import extra columns
When import has extra column, importing doesn't work as expected

### PR DESCRIPTION
**Pull request by tohjh**
Closes #151 
Closes #184 
Closes #157
Closes #148
Closes #147
Closes #153

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/ImportCommand.java [hunk 1]
```diff
@@ -5,42 +5,40 @@
...
     public static final String COMMAND_WORD = "import";
     public static final String MESSAGE_USAGE = COMMAND_WORD + ": Imports person data from a CSV file.\n"
-            + "Parameters: FILE_PATH"
-            + "[" + PREFIX_PATH + "FILE_PATH]\n"
-            + "Example: " + COMMAND_WORD + " " + PREFIX_PATH + "data/persons.csv";
+        + "Parameters: FILE_PATH"
+        + "[" + PREFIX_PATH + "FILE_PATH]\n"
+        + "Example: " + COMMAND_WORD + " " + PREFIX_PATH + "data/persons.csv";
+    public static final String CORRECT_HEADER_USAGE =
+        "Your header should be Name, Phone, Email, Telegram, Tags, Github, Assignments, WeeksPresent"
```
Comment (Incogdino) [inline src/main/java/seedu/address/logic/commands/ImportCommand.java:32]: I feel like we should be less directed towards the user and more like returning a message such as "The header of the csv file should be Name, Phone, Email, Telegram, Tags, Github, Assignments, WeeksPresent"

File: src/main/java/seedu/address/logic/commands/ImportCommand.java [hunk 2]
```diff
@@ -51,109 +49,42 @@ public CommandResult execute(Model model) throws CommandException {
...
-                    tag = tag.substring(1, tag.length() - 1); // Remove the brackets
-                }
-                if (!tag.isEmpty()) {
-                    tags.add(new Tag(tag));
-                }
+            if (newPersons.isEmpty()) {
+                throw new CommandException("There is no person data present");
             }
+            model.replaceAllPersons(newPersons);
+        } catch (IOException | CsvValidationException | DuplicatePersonException | CommandException e) {
```
Comment (Incogdino) [inline src/main/java/seedu/address/logic/commands/ImportCommand.java:78]: I think this can be better if we separate the exceptions out and handle them separately.

File: src/main/java/seedu/address/logic/parser/CsvAssignmentParser.java [hunk 3]
```diff
@@ -0,0 +1,69 @@
...
+
+    /**
+     * Processes each assignment entry by validating the name and score, and adds it to the assignments map.
+     *
+     * @param assignment  string representing a single assignment
+     * @param assignments map to store validated assignments
+     * @param model       the application model
+     * @throws CommandException if assignment name or score is invalid
+     */
+    public static void processAssignment(String assignment, Map<String, Assignment> assignments, Model model)
```
Comment (Incogdino) [inline src/main/java/seedu/address/logic/parser/CsvAssignmentParser.java:48]: I don't think this method was used anywhere outside of this class, might be better to make this private.

File: src/main/java/seedu/address/logic/parser/CsvAttendanceParser.java [hunk 4]
```diff
@@ -0,0 +1,32 @@
...
+
+import seedu.address.logic.parser.exceptions.ParseException;
+/**
+ * Parses attendance data from a CSV field, extracting the weeks present as a set of integers.
+ */
+public class CsvAttendanceParser {
+    /**
+     * Parses the weeksPresent field into a set of integers.
+     *
+     * @param weeksField string representing weeks present, separated by commas
```
Comment (Incogdino) [inline src/main/java/seedu/address/logic/parser/CsvAttendanceParser.java:14]: Not sure if this is very important, but the java coding standard specifies a punctuation behind each param field. I think most of the comments lacks the punctuation.

File: src/main/java/seedu/address/logic/parser/CsvAttendanceParser.java [hunk 5]
```diff
@@ -0,0 +1,32 @@
...
+     * @return a set of integers representing weeks present
+     * @throws ParseException if any week value is invalid
+     */
+    public static Set<Integer> parseWeeksPresent(String weeksField) throws ParseException {
+        Set<Integer> weeksPresent = new HashSet<>();
```
Comment (Incogdino) [inline src/main/java/seedu/address/logic/parser/CsvAttendanceParser.java:19]: I feel that we can include a `requireNonNull` check here just in case. The same applies to the other parsers?

**Review by Incogdino — COMMENTED** [review]
Added some feedback regarding parts of the code
